"$schema": http://json-schema.org/draft-04/schema#
"$id": https://example.com/product.schema.json
title: DCIM v1
description: Version 1 of config file
type: object
required:
- version
- agents
properties:
  version:
    description: The unique identifier for a product
    type: string
    const: '1'
  agents:
    description: List of DCI agents
    type: array
    items:
      type: object
      required:
      - type
      - component_name
      - tests
      properties:
        type:
          type: string
          description: Type of the DCI Agent
          enum:
          - rhel
          - openshift
          - openshift-app
        component_name:
          type: string
          minLength: 4
        tests:
          type: array
          minItems: 1
          items:
            required:
            - name
            - target_versions
            - app_versions
            - steps
            type: object
            properties:
              name:
                type: string
              target_versions:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  type: string
              app_versions:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  type: string
              variables:
                type: object
                additionalProperties:
                  type: string
              setup: &steps
                type: array
                minItems: 0
                uniqueItems: true
                items:
                  type: object
                  additionalProperties: true
                  minProperties: 2
                  required:
                  - name
                  properties:
                    name:
                      type: string
                      minLength: 4
              steps: 
                <<: *steps
                minItems: 1
    


